spring.application.name=accounting-app-demo


# ==================== DATABASE ====================
spring.datasource.url=jdbc:postgresql://postgres:5432/account
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==================== JPA / AUTO DDL ====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==================== JWT ====================
auth.token.expirationInMils=72000000
auth.token.jwtSecret=36763979244226452948404D635166546A576D5A7134743777217A25432A462D


# Logging
logging.level.com.rbac=DEBUG
logging.level.org.springframework.security=DEBUG

# Swagger
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs


server.port=8080